# Generated by Django 5.2.4 on 2025-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
