# Generated by Django 5.2.4 on 2025-07-11 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_gatepass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
