# Generated by Django 5.2.4 on 2025-07-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_gatepass_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='uuid',
        ),
    ]
