# Generated by Django 5.2.4 on 2025-07-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_gatepass_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
